### ISSUE TITLE
Setting maxWidth hide toggle

### ISSUE THREAD

**Issue by grayter1** [somewebmedia/hc-offcanvas-nav#1]
If maxWidth property was set to 980 (as you provided in your github doc) toggle button hides. Also adding display: block for this toggle is not working because navigation menu is blank after toggle click.

**Comment by somewebmedia** [comment]
Hi @grayter1, sorry for late response, I was on vacation. Can you provide any demo for this?

**Comment by somewebmedia** [comment]
Hi @grayter1, sorry for late response, I was on vacation. That is the desired behaviour, because you don't need a toggle button when the offcanvas nav is disabled.

**Comment by somewebmedia** [comment]
The `maxWidth` is referred to screen width at which to show/hide the nav and the toggle.
