### ISSUE TITLE
How to make it expanded by default ?

### ISSUE THREAD

**Issue by nurbeknurjanov** [somewebmedia/hc-offcanvas-nav#10]
I mean, when I open some menu, clicked, page is refreshed, then go back to menu. It opens from scratch, from root.
Exactly I would like to have opened root, opened some level, where the link was clicked, whenever page is refreshed or not.
How ?

**Comment by somewebmedia** [comment]
Good question! I'll have to address that in a future release.

**Comment by nafg** [comment]
:+1:

**Comment by vahidalvandi** [comment]
good feature

**Comment by kolor** [comment]
That would be an amazing feature for navigation - Active menu/ or pre expanded! Great work by the way! Really appreciate the work you put in!

**Comment by emage** [comment]
Waiting on this feature as well - open to the currently active category - not starting the drill down all over again.

**Comment by somewebmedia** [comment]
This is very similar to this request https://github.com/somewebmedia/hc-offcanvas-nav/issues/14
Check my answer there and we'll see where it goes.

**Comment by somewebmedia** [comment]
Hello everybody, that days is finally here! The latest version of the plugin brings you the desired feature.

New [options](https://github.com/somewebmedia/hc-offcanvas-nav#options): `expanded`, `closeOpenLevels`
New [data attribute](https://github.com/somewebmedia/hc-offcanvas-nav#data-attributes): `data-nav-active`

Check the repo readme for details on how to use them.

Cheers.
