### ISSUE TITLE
Momentum scrolling

### ISSUE THREAD

**Issue by Fullbrains** [somewebmedia/hc-offcanvas-nav#11]
Adding `-webkit-overflow-scrolling: touch` to `.nav-container` will result in a wrong clipping and z-index of the overlap menus.

```
.hc-offcanvas-nav .nav-container {
    position: fixed;
    z-index: 9998;
    top: 0;
    width: 280px;
    height: 100%;
    max-width: 100%;
    max-height: 100%;
    box-sizing: border-box;
    transition: transform .4s ease;
    -webkit-overflow-scrolling: touch;
}
```

**Comment by somewebmedia** [comment]
`-webkit-overflow-scrolling: touch;` is not a standard feature, but if you want to use it, use it on `.nav-content` element because it holds the each nav and subnav content. That way you shouldn't have any problems with overlapping.
