### ISSUE TITLE
Ajax does not proceed?

### ISSUE THREAD

**Issue by programmersindonesia** [somewebmedia/hc-offcanvas-nav#12]
Ajax does not proceed?
When I click first menu item in a menu created with [`hcOffcanvasNav`](https://github.com/somewebmedia/hc-offcanvas-nav), the Ajax result does not show.

I want to display it like this: when I click on the first `li`, the childs appears. And when those childs are clicked, the sub-childs appears.

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script>
    <script src="hc-offcanvas-nav.js?ver=3.2.0"></script>

    <div id="container">
      <div id="nav">
        <div id='state-list'>
          <div id='city-list'>
          </div>
        </div>
      </div>
    </div>
    
    <script>
    var Nav;
    Nav = $('#nav').hcOffcanvasNav({
      maxWidth: false,
      levelTitles: true,
      closeOnClick: false
    });
    </script>

    <script src="jquery-3.2.1.min.js" type="text/javascript"></script>
    <script>
    $(document).ready(function() {
      $('.state').click(function(e) {
        e.preventDefault();
        $.ajax({
          type: "POST",
          url: "index.php",
          data: {
            activeMenu: this.id
          },
          success: function(data) {
            $("#state-list").html(data);
          }
        });
      });

      $('.city').click(function(e) {
        var teks = $(".linka").closest('li').attr('value');
        e.preventDefault();
        $.ajax({
          type: "POST",
          url: "index.php",
          data: {
            activeMenu: teks,
            activeSubMenu: this.id
          },
          success: function(data) {
            $("#city-list").html(data);
          }
        });
      });
    });
    </script>
    
[Not Show][1]

I need 
[show][2]

  [1]: https://i.stack.imgur.com/Zt3dx.png
  [2]: https://i.stack.imgur.com/ou5EQ.png 
@somewebmedia

**Comment by somewebmedia** [comment]
You should call `Nav.update(true);` after updating your nav html.

**Comment by programmersindonesia** [comment]
Why not open of canvas?
<!DOCTYPE html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:200,300,400,600,700">
    <link rel="stylesheet" href="demo.css">
    <style>
      .hc-nav-trigger {
        right: 20px;
      }

      .hc-nav-trigger span,
      .hc-nav-trigger span::before,
      .hc-nav-trigger span::after {
        background: #fff;
      }
    </style>
   <script src="jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script>
    <script src="hc-offcanvas-nav.js?ver=3.2.0"></script>
    
  </head>

  <body>

    <div id="container">
      <nav id="nav">
    		<ul class="link" > 
        <?php 
          require_once("model/dbconn.php");
     	 require_once("model/sql.php");
     	  $query = new sql(); 
      	$data = $query->getMenu();
   		 $key = $data[1]; 
          foreach($key as $menu) 
          {
          	 if($menu['idnegara'])
        {
        ?>
          	<li value="<?php echo $menu['idnegara']; ?>" class=" nav-parent">
<a href="#" name="link" class="state"  id="<?php echo $menu['idnegara']; ?>"  data-id="<?php echo $menu['idnegara']; ?>" >
 <?php echo $menu['namanegara']; ?><span class="nav-next"></span>
</a>

        	</li>
        <?php
          }
          }
        ?>
      </ul>
          </nav>
<script>
$(document).ready(function() {
	// $(document).on( 'click', '.state',function(e) {
 $('.state').click(function(e) {
 	
 	
  	var parent = $(this).parents('li');

    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "state.php",
      data: {
        activeMenu: this.id
      },
      success: function(data) {
      	parent.parent().find('li>ul').remove();
   			 parent.append(data);
parent.update(true);

      }
    });
  });
 
   $(document).on( 'click', '.city',function(e) {
   		var parent = $(this).parents('li');
    var teks = $(".linka").closest('li').attr('value');
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "city.php",
      data: {
        activeMenu: teks,
        activeSubMenu: this.id
      },
      success: function(data) {
      parent.parent().find('li>ul').remove();
   	 parent.append(data);
      parent.update(true);
      
      }
    });
  });


});
	    parent = $('#nav').hcOffcanvasNav({
            maxWidth: false,
            levelTitles: true,
            closeOnClick: false
          });
</script>
    </div>
  </body>
</html>

**Comment by programmersindonesia** [comment]
Why Not open ofcanvas ? pleace help me
		<!DOCTYPE html>
		<html>
		  <head>
			<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
			<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
			<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:200,300,400,600,700">
			<link rel="stylesheet" href="demo.css">
			<style>
			  .hc-nav-trigger 
			   {
				right: 20px;
			   }
			  .hc-nav-trigger span,
			  .hc-nav-trigger span::before,
			  .hc-nav-trigger span::after {
				background: #fff;
			  }
			</style>
			    <script src="jquery-3.2.1.min.js" type="text/javascript"></script>
			    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script>
				<script src="hc-offcanvas-nav.js?ver=3.2.0"></script>
		  </head>

		<body>
			<div id="container">
				<nav id="nav">
    		       <ul class="link" > 
						<?php 

						  require_once("model/dbconn.php");
						  require_once("model/sql.php");
						  $query = new sql(); 
						  $data = $query->getMenu();
						  $key = $data[1]; 
						  foreach($key as $menu) 
						  {
							
							 if($menu['idnegara'])
						  {
						?>
     
                	<li value="<?php echo $menu['idnegara']; ?>" class=" nav-parent">	
						<a href="#" name="link" class="state"  id="<?php echo $menu['idnegara']; ?>"  data-id="<?php echo $menu['idnegara']; ?>" >
							<?php echo $menu['namanegara']; ?><span class="nav-next"></span>
						</a>
					</li>
						<?php
						  }
						  }
						?>
           
					</ul>
				</nav>

						<script>
						$(document).ready(function() {
						$(document).on( 'click', '.state',function(e) {
						 $('.state').click(function(e) { 	
							var parent = $(this).parents('li');
							e.preventDefault();
							$.ajax({
							  type: "POST",
							  url: "state.php",
							  data: {
								activeMenu: this.id
							  },
							  success: function(data) {
								parent.parent().find('li>ul').remove();
									 parent.append(data);
                                                                    parent.update(true);
							  }
							});
						  });
						   $(document).on( 'click', '.city',function(e) {
								var parent = $(this).parents('li');
							var teks = $(".linka").closest('li').attr('value');
							e.preventDefault();
							$.ajax({
							  type: "POST",
							  url: "city.php",
							  data: {
								activeMenu: teks,
								activeSubMenu: this.id
							  },
							  success: function(data) {
							  parent.parent().find('li>ul').remove();
							 parent.append(data);
                                                         parent.update(true);
							  }
							});
						  });
						});
                                                                parent.update(true);
								parent = $('#nav').hcOffcanvasNav({
									maxWidth: false,
									levelTitles: true,
									closeOnClick: false
								  });
						</script>
				</div>

			</body>
		</html>
