### ISSUE TITLE
add rtl

### ISSUE THREAD

**Issue by vahidalvandi** [somewebmedia/hc-offcanvas-nav#13]
please add rtl 

just change text nav and icon 
![image](https://user-images.githubusercontent.com/7871623/50338709-73bc5b00-052a-11e9-9081-511bfa6623cb.png)

**Comment by vahidalvandi** [comment]
i fixed it by add this code 

`
.hc-offcanvas-nav li {
    text-align: right !important;
}

span.nav-next, .hc-offcanvas-nav li.nav-back span {
 
    left: 0 !important;
    right: unset !important;
}

.hc-offcanvas-nav li.nav-parent .nav-item {
     padding-right: 25px !important;
}

`

**Comment by somewebmedia** [comment]
Added it as a native support now. Use `rtl` option.
