### ISSUE TITLE
open inner menus directly

### ISSUE THREAD

**Issue by itsmekps** [somewebmedia/hc-offcanvas-nav#14]
is it possible to open the directly second or third stack of the menu on a click of a button or link

as in the the below screenshot, is it possible to open Mobile Phones menu directly on a click of a link or button??

![image](https://user-images.githubusercontent.com/24510563/50452287-2d6a6000-095f-11e9-9f0a-bc15f399a499.png)

**Comment by hacker1122** [comment]
> is it possible to open the directly second or third stack of the menu on a click of a button or link
> 
> as in the the below screenshot, is it possible to open Mobile Phones menu directly on a click of a link or button??
> 
> ![image](https://user-images.githubusercontent.com/24510563/50452287-2d6a6000-095f-11e9-9f0a-bc15f399a499.png)

Same question i just want to make. Is it possible?

**Comment by stefas1** [comment]
This is the best plugin we've ever used in terms of stability and ease of use. 
Opening in a specific level (active item) would make it the perfect solution... We would really like to see this feature...

**Comment by somewebmedia** [comment]
Ok I have something for this.

Lets say we have this example:
```
Level: 0
|
|-Item
|   |
|   |-Level: 1, Index: 1
|   |
|   |--Item
|   +--Item
|        |
|        |-Level: 2, Index: 1
|        |
|        |----Item
|        +----Item
+-Item
    |
    |-Level: 1, Index: 2
    |
    |--Item
    +--Item
         |
         |-Level: 2, Index: 2
         |
         |----Item
         +----Item
```
Each level has its own index that is relative to that level, not the parent. Which means if you have complex multilevel navigation, it can be tricky to know what you want to open.

So in the above example you would call the method something like this: `Nav.open(2, 2);`

You can test this feature in the `open-inner` branch and let me know what you think. I've already setup this to work in the demo.

**Comment by stefas1** [comment]
Thank you very much. We will try and let you know...

**Comment by somewebmedia** [comment]
I've merged this into master and published a new version with few new features.

With the above `.open()` method, the new options added are `expanded`, `closeOpenLevels`, and also new `data-nav-active` attribute.

Check the repo readme for details on how to use them.
