### ISSUE TITLE
Website says account suspended

### ISSUE THREAD

**Issue by nafg** [somewebmedia/hc-offcanvas-nav#17]

**Comment by Phoenixy** [comment]
A demo is available here: https://www.jqueryscript.net/demo/Multi-Level-Sidebar-Menu-HC-MobileNav/

**Comment by nafg** [comment]
I know, the point is that the repo description and the readme are outdated

**Comment by somewebmedia** [comment]
New demo is here: http://somewebmedia.github.io/hc-offcanvas-nav/
