### ISSUE TITLE
Keep selected item in nested menu

### ISSUE THREAD

**Issue by JoseWalker** [somewebmedia/hc-offcanvas-nav#25]
There is any way in which the menu can remember the selected menu within a nested menu? this is to avoid clicking multiple times when a menu within a menu has been selected. 

Any plans to implement that?

Regards,

Jose.

**Comment by somewebmedia** [comment]
You mean when you close the menu and open it again, you would like for it to open on the specific submenu that was previously open?

**Comment by somewebmedia** [comment]
Check the latest version and these new features:

New [options](#options): `expanded`, `closeOpenLevels`
New [data attribute](#data-attributes): `data-nav-active`
