### ISSUE TITLE
Can the BACK label be able to pull the previous levelTitles?

### ISSUE THREAD

**Issue by emage** [somewebmedia/hc-offcanvas-nav#26]
Instead of always the default BACK regardless of the level depth, I was trying to setup where the BACK button label should pull the previous levelTitle - this make it easier to see how far in and where you are at. Im using the overlap method with no levelSpacing.

Example:

< Training
 - Online
 - Campus

In the above - clicking Training will take you back to the  main level/sub level of TRAINING.

Thanks in advance!

**Comment by somewebmedia** [comment]
Hi, thanks for the suggestion. I just added option `levelTitlesAsBack`
