### ISSUE TITLE
Remove code for desktop menu

### ISSUE THREAD

**Issue by Phoenixy** [somewebmedia/hc-offcanvas-nav#27]
Hello,
I love your menu and I'm using it for awhile, but I only need it for mobilmenu (below 1024px). I have a different menu for bigger resolutions (PC).
Your menu has the regular version and the mobile version (created from the html template by Javascript).
Could somehow the regular version be erased? It's just hidden (display: none;) for me (that's a lot of html code without use on my website).

**Comment by somewebmedia** [comment]
Hi, you can now use `removeOriginalNav` option set to `true`.

**Comment by Phoenixy** [comment]
Ohh, amazing. Thank you!!!
