### ISSUE TITLE
How to make HTML menu added not at the end of the page layout and immediately after the main menu?

### ISSUE THREAD

**Issue by UrchenkoV** [somewebmedia/hc-offcanvas-nav#28]
Hello.

Have WordPress appeared new rules, need to mobile menu supported governance with have but your script menu inserts in late markup this not allows use menu with have with the help TAB. How do I change the code so that the markup is inserted after the main menu?

Add a non-minified CSS file to the source.

Can you fix the script to support keyboard controls?

**Comment by somewebmedia** [comment]
I can make nav to be inserted to the beginning of the body instead of the end. Due to css restrictions it can't go inside the content.

Can you clarify what you exactly mean by keyboard controls? Any example?

**Comment by UrchenkoV** [comment]
I already did it myself. Thanks.

**Comment by somewebmedia** [comment]
Nav is now prepended to the body by default and full keyboard support has been added in the latest release.
