### ISSUE TITLE
Clone entire <li> content into nav menu

### ISSUE THREAD

**Issue by plamenradev** [somewebmedia/hc-offcanvas-nav#29]
Hey, thanks for the great plugin, you have done great job!

I was wondering if the plugin could works with the following structure without trim the '.dont-trim' element:
```
<nav id="main-nav">
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
    <li class="special-item"><div class="dont-trim"><a href="#">SPECIAL</a></div></li>
  </ul>
</nav>
```

Now, after plugin initialization .dont-trim element disappears.  Is it possible to add some special class like '.special-item' to the `<li>` element, for example, which tells the plugin to not trim the inner content and keep it in its original structure?

Here is why I need this option. Lets consider that you want to include an entire widget as a menu item. The widget could contains a lot of `<div>` elements with some CSS classes for styling and `<a>` tag in the deep. For example:
```
<div class="special-offer-wrapper">
  <div class="btn-container">
    <a href="some-url">SPECIAL OFFER</a>
  </div>
</div>
```
This widget could be dynamically loaded, so could be everything, and will be great if is possible to keep its entire original code, as a different special menu item.

Hope this feature could makes the plugin more flexible.

Thanks in advance!
Cheers!

**Comment by dominikkucharski** [comment]
@plamenradev did you found a solution?

**Comment by dominikkucharski** [comment]
I used some dirty hack to fix this issue (but I wish there would be real solution with your idea). 

I've added custom content this way:
```
<ul class="c-mobile-contact-info">
        <li class="raw">
          <div class="mb-1">
            <span class="font-bold mr-2">Email:</span> <span class="js-fake-link" data-link="mailto:email@email.com">mailto:email@email.com</span>
          </div>
          <div>
            <span class="font-bold mr-2">Telefon:</span>  +XX XXX XXX XXX
          </div>
        </li>
</ul>
```

Additionally, I've used this jQuery code to create fake links:
```
$('.js-fake-link').on('click', function(e){
    e.preventDefault();
    window.location.href = $(this).data('link');
  });
```

@somewebmedia It would be great if list item with some class (for example .raw or .dont-trim) would be ignored by the plugin and cloned without any changes 🙏

**Comment by somewebmedia** [comment]
Hello all, unfortunately custom elements would much complicate things. The way things work now is the plugin takes the original nav and traverses it re-creating it as a new one. So it only basically looks for `ul`,`li` and `a`, and whatever is inside `a` gets cloned with it.

I could theoretically, with the use of `data-` on the `li`, tell the plugin to clone the content from the `li` and don't go any further into that item. But that would mean that if you have any submenu inside of it, it would be ignored for further traversing. Also if you have `a` somewhere inside it (like in the top example), it would loose ability to close the menu on click (if that option is enabled).

So what you guys think?

**Comment by dominikkucharski** [comment]
@somewebmedia I think we can live with the limitations pointed by you. We will just follow the rules (like no submenus in the cloned `li`) and use the new functionality.

**Comment by somewebmedia** [comment]
Can you please check and test your content with `custom_content` branch and let me know if everything works for you, I don't have much time to properly test it.

Use it like this:

`<li data-nav-custom-content>Your custom content</li>`

**Comment by dominikkucharski** [comment]
I'm on it.

**Comment by dominikkucharski** [comment]
@somewebmedia everything is working perfectly. I've tested it in the latest versions of Chrome, Safari, Edge, and Opera. I couldn't test it on IE11, because the demo JavaScript code was too modern for this browser. 

There is only one thing which can be changed. I've covered it in the pull request #31.

**Comment by somewebmedia** [comment]
Pushed with new version `v3.4.3`.
Thanks!

**Comment by somewebmedia** [comment]
There was a bug, when updating the nav custom content would disappear. I fixtedit! Use the latest version of the plugin.
