### ISSUE TITLE
Change language from default options

### ISSUE THREAD

**Issue by Halmeth** [somewebmedia/hc-offcanvas-nav#34]
Hello everyone! Hope you are doing ok!

I have a doubt. Can you edit the text from "close" and "back" default options in the nav? I'm asking this because I want to change them to another language.

![cap-2020](https://user-images.githubusercontent.com/62158047/82586589-6c551300-9b5d-11ea-86b9-7ca3a58713f1.jpg)

Thanks for reading.

**Comment by somewebmedia** [comment]
Yes, use `labelClose` and `labelBack` options.

Example:
```js
$('#main-nav').hcOffcanvasNav({
  labelClose: 'Zatvori',
  labelBack: 'Nazad'
});
```

**Comment by Halmeth** [comment]
Nice! Thanks!
