### ISSUE TITLE
How to open nav with screen swipe on mobile devices

### ISSUE THREAD

**Issue by gaaytrimaa** [somewebmedia/hc-offcanvas-nav#35]
Hello somewebmedia , I hope you are doing fine. The navbar would be more robust if we could add a feature to open it on mobile devices through swipe of screen as is available in native apps. I would like to contribute if you wish.

Thank you.

**Comment by somewebmedia** [comment]
I'll have to think about this.

**Comment by somewebmedia** [comment]
I thought about it and implemented it. It's in the latest version. :)

Haven't tested it on iPhone tho, only on Android device.

**Comment by gaaytrimaa** [comment]
So, nice of you for adding this native app like feature.
It would be very nice if there is an option to change text color and background color of the navigation from a single place rather than editing the demo.css file at multiple places with hex code.

**Comment by somewebmedia** [comment]
You should not use the demo.css file, it serves just for the repository demo purposes.

In fact you shouldn't edit any of the files from this plugin. If you want to change the look of the nav there are two ways:

- Via scss, by assign your colors to predefined vars and importing the main scss into your scss:

```scss
$hc-offcanvas-nav-background-color: #0d0d0d;
$hc-offcanvas-nav-text-color: #dedede;

@import 'path-to-nav/hc-offcanvas-nav/src/scss/hc-offcanvas-nav';
```

- Via regular css, by just overriding the styles you want in your css:
```css
.hc-offcanvas-nav .nav-container,
.hc-offcanvas-nav .nav-wrapper,
.hc-offcanvas-nav ul {
    background-color:  #0d0d0d;
}
```
