### ISSUE TITLE
SCSS theme arrow colour is hardcoded

### ISSUE THREAD

**Issue by bossloper** [somewebmedia/hc-offcanvas-nav#37]
The SCSS theme has hardcoded #fff for the subnav arrows so they do not show if the nav background is overriden to white:
https://github.com/somewebmedia/hc-offcanvas-nav/blob/master/src/scss/_theme.scss#L163-L164

Same for prev/next:
https://github.com/somewebmedia/hc-offcanvas-nav/blob/master/src/scss/_theme.scss#L195-L196

Suggest they are set as $hc-offcanvas-nav-text-color

**Comment by somewebmedia** [comment]
Done. Good catch, thanks!
