### ISSUE TITLE
Keep open on page refresh in a selected item 

### ISSUE THREAD

**Issue by Sebastiangperez** [somewebmedia/hc-offcanvas-nav#38]
I wanna ask if its possible keep the menu open when the page refresh or if you select an item. 
Maybe there is a way that i can retrieve the selected item and stored on a localstorage variable. there is a way to do that ? 
Besides, it is a way that you can disable the offcanvas an used has a side bar ?

**Comment by somewebmedia** [comment]
To open nav by default when page opens set [`expanded`](https://github.com/somewebmedia/hc-offcanvas-nav#options) option to `true`.

Retrieving selected item currently isn't possible, but it would be a good feature, I'll try to implement it.

Could you clarify more the last sentence, I did not quite understood it.

**Comment by Sebastiangperez** [comment]
Thanks for your response.
What i mean in the last sentence is if there is a possibility to use the same plugin without the hamburger button and using simple as a side menu.

**Comment by somewebmedia** [comment]
Well it's not meant to be used like that but you could by using `{ expanded: true }` and hiding the hamburger with simple css.

**Comment by somewebmedia** [comment]
I've pushed a new plugin version. To store and retrieve the selected open level you can now do it like this:

```js
// call our plugin
var Nav = $menu.hcOffcanvasNav({});

// attach events and store levels and indexes in local storage
Nav.on('open.level', (e, l, i) => {
  localStorage.setItem('NavLevel', l);
  localStorage.setItem('NavIndex', i);
}).on('close.level', (e, l, i) => {
  localStorage.setItem('NavLevel', l);
  localStorage.setItem('NavIndex', i);
}).on('close', () => {
  localStorage.removeItem('NavLevel');
  localStorage.removeItem('NavIndex');
});

// read from local storage and open specific level and index if there were any previously open
if (localStorage.getItem('NavLevel')) {
  Nav.open(localStorage.getItem('NavLevel'), localStorage.getItem('NavIndex'));
}
``` 

This is just an example, you can tweak it per your needs.

**Comment by Sebastiangperez** [comment]
Nice add man, yep, something like  that i needed. 
This is very useful 
Thanks.
