### ISSUE TITLE
Column menu

### ISSUE THREAD

**Issue by brendan8c** [somewebmedia/hc-offcanvas-nav#39]
How to make a menu in a column?
I have it in a line and a scroll bar below.

I set css in the settings 
**display: flex;
flex-direction: column;**
That helped. But I would like to know if there is a more normal way to do this.

```
<div id="main-nav">
    <ul class="header__main_wrap">
       <li><a href="#" class="header__main--page">products</a></li>
       <li><a href="#" class="header__main--page">rooms</a></li>
       <li><a href="#" class="header__main--page">services</a></li>
       <li><a href="#" class="header__main--page">contacts</a></li>
     </ul>
 </div>
```

```
$(function() {
    jQuery(document).ready(function($) {
        $('#main-nav').hcOffcanvasNav({
            disableAt: 530,
            expanded: false,
            swipeGestures: true,
        });
    });
});
```

Look here 
1) _https://photos.app.goo.gl/eukJGRNqdgY12y2x5_
2) _https://photos.app.goo.gl/Hp8SBuTj8Q3bXMeF8_

**Comment by somewebmedia** [comment]
It seems you are doing that with your css code somewhere. I've updated the plugin, can you try adding this new option to your code `keepClasses: false`, and let me know if the css problem is still there?

**Comment by brendan8c** [comment]
Problem still exists.
I uploaded this site to the hosting, you can see for yourself.
http://xx.tw1.ru
I also temporarily added these changes to my repository. You can download it and watch
https://github.com/brendan8c/Furnito

**Comment by somewebmedia** [comment]
It's because you're still using the previous version of the plugin. Run `npm update` so it fetches the latest lib version, then run your gulp.

**Comment by brendan8c** [comment]
Yes it worked! Thank )
