### ISSUE TITLE
Position fixed ignored on element when closing nav

### ISSUE THREAD

**Issue by robertsLando** [somewebmedia/hc-offcanvas-nav#4]
When closing nav menu with a custom toggle placed in a top bar with position fixed cause the top bar to lose the fixed position when scrolling (so it is scrolled too when scrolling and doesn't remain visible to user on top). 

This is caused from the translate3D property added to the toggle when opening/closing the nav (or a level). To fix this just remove the 3d property on nav close, with this edits the code works: 

```javascript
const setTransform = (() => {
        const transform = browserPrefix('transform');

        return ($el, val) => {
          if (transform) {
            const x = SETTINGS.side === 'left' ? val : -val;
            //if x is 0 remove the translate3d property
            if(x > 0)
              $el.css(transform, `translate3d(${x}px,0,0)`);
            else
              $el.css(transform, '');
          }
          else {
            $el.css(SETTINGS.side, val);
          }
        };
      })();
```

**Comment by somewebmedia** [comment]
Fix included in the current `new` branch: https://github.com/somewebmedia/hc-offcanvas-nav/commit/c924637f2add085629f36a74ce3fd0aa538f2cf2
