### ISSUE TITLE
Brand logo on header

### ISSUE THREAD

**Issue by rajeshdoot** [somewebmedia/hc-offcanvas-nav#42]
How to add brand logo on header. Icon in the right is enough to closing. How to add brand logo in left side.

**Comment by somewebmedia** [comment]
If you want to add custom content in the menu use `data-nav-custom-content` data attribute on the list element. And then style it in your css if needed.

Example:
```
    <li data-nav-custom-content>
      <img src="path/to/your/logo.jpg">
    </li>
```

**Comment by rajeshdoot** [comment]
Thanks

**Comment by 5ulo** [comment]
any way to put the logo inside `navTitle` so it will show instead of default title `All Categories` on the first level?

**Comment by somewebmedia** [comment]
Here is the same question: https://github.com/somewebmedia/hc-offcanvas-nav/issues/47
