### ISSUE TITLE
Change position of close button to upper left or upper right menu?

### ISSUE THREAD

**Issue by zilveer** [somewebmedia/hc-offcanvas-nav#44]
Hi,
I would prefer, which is more or less common for all kind of navigations today to place the Close button on the upper left or upper right corner of the menu, and also switch it to a Cross (X), and have "Close" as a label.

What do you think ?

regards

**Comment by somewebmedia** [comment]
You can always pass a custom HTML element as `labelClose` and style it per your needs.

Example:

```js
var closeButton = document.createElement('div');
closeButton.className = 'nav-close-button';
closeButton.title = 'Close';

var Nav = new hcOffcanvasNav('#main-nav', {
    labelClose: closeButton
});
```

Or with jQuery:

```js
$('#main-nav').hcOffcanvasNav({
    labelClose: $('<div class="nav-close-button" title="Close">')[0]
});
```

**Comment by zilveer** [comment]
Thx I know that I can customize it even in CSS, but would be better to have it as standard in this library I think. 

Regards

**Comment by somewebmedia** [comment]
I'll think about this. Maybe if you could provide some screenshots examples for me to consider.
