### ISSUE TITLE
Missing opening/closing effect, if size was changed

### ISSUE THREAD

**Issue by Phoenixy** [somewebmedia/hc-offcanvas-nav#45]
Hi,
I've just updated from 4.2.5 to 5.0.10, and I found a new issue.
If I open the webpage in a full screen window (above 1024px), then I change its size (below 1024px, so the PC menu is replaced with the mobile menu), and I click to open the mobile menu, there is no effect, and there's no effect when closing either.
If the page was opened below 1024px, then the menu opening/closing working fine.

I hope you understood me, it's quite hard to explain this.
I attached an image (that appears for a second, when I close the menu if the website was first loaded with above 1024px width).
![weird](https://user-images.githubusercontent.com/801036/91415837-dfea7880-e84e-11ea-9daf-eef112b0fc98.png)

**Comment by somewebmedia** [comment]
Fixed with the new version.
