### ISSUE TITLE
How to replace logo on navTitle Text.

### ISSUE THREAD

**Issue by rajeshdoot** [somewebmedia/hc-offcanvas-nav#47]
![menu](https://user-images.githubusercontent.com/13962175/92558547-6742dd80-f28c-11ea-8dd7-36db5e7b7ad7.jpg)

**Comment by somewebmedia** [comment]
I'll see to implement this feature soon.

**Comment by somewebmedia** [comment]
One question tho, if `navTitle` is set as HTML element (image), what should be used as a back label on the next level when `levelTitleAsBack` is set to true?

**Comment by glavrjk** [comment]
> One question tho, if `navTitle` is set as HTML element (image), what should be used as a back label on the next level when `levelTitleAsBack` is set to true?

I consider that the logo should only be shown in the main view, in the sub-sequences it should show the name of the parent, as it does currently.

**Comment by somewebmedia** [comment]
The name of the parent is the `navTitle` for the first level.

**Comment by glavrjk** [comment]
well you can put `navTitle `like `html `or `string ` and the rest works like currently

**Comment by somewebmedia** [comment]
I can make the back button have "Back" text if `navTitle` is html object.

>  In other way, you know i updated the library to 6 and i had to do a rollback because all my custom css was destroyed :/

Please open a ticket for that so I can explain the css changes I made in the version 6.

**Comment by somewebmedia** [comment]
Added this feature in the latest version.
