### ISSUE TITLE
IE11 complains 'EventTarget' is undefined and Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by matchman72** [somewebmedia/hc-offcanvas-nav#49]
using IE 11.0.210 on Windows 10, browse to https://somewebmedia.github.io/hc-offcanvas-nav/

IE console shows 

`SCRIPT5009: 'EventTarget' is undefined
hc-offcanvas-nav.js (11,24689)`

`SCRIPT438: Object doesn't support property or method 'assign'
hc-offcanvas-nav.js (11,651)`

and the toggle navigation won't work

**Comment by somewebmedia** [comment]
Fixed with the newest major version.
