### ISSUE TITLE
Disable swipe gesture when specific elements are being touched

### ISSUE THREAD

**Issue by Aurugorn** [somewebmedia/hc-offcanvas-nav#50]
Awesome plugin, it works great.

Currently the menu is always opening and closing when you swipe gesture from the edge of your mobile.
We have a slider element on our page which is full width and whenever we swipe this slider from left to right it causes the menu to open.
How do we prevent the menu from opening when we slide the slider?

**Comment by somewebmedia** [comment]
Hi, thanks :)
Just set `swipeGestures: false`
