### ISSUE TITLE
levelTitleAsBack is ignored

### ISSUE THREAD

**Issue by 5ulo** [somewebmedia/hc-offcanvas-nav#51]
I suppose the level title should be clickable and contain arrow back instedad of having another item in the navbar called `All categories` or `Back` (in default state). 
```
document.addEventListener('DOMContentLoaded', function() {

  var Nav = new hcOffcanvasNav('#main-nav', {
    disableAt: 3000,
    customToggle: '.toggle',
    navTitle: 'All Categories',
    levelTitles: true,
    levelTitleAsBack: true
  });

});
```
I made a [Codepen](https://codepen.io/5ulo/pen/mdEVbWY)

**Comment by somewebmedia** [comment]
Actually `levelTitleAsBack` means that the "Back" button should use the previous level title as it's text, so the current behaviour is the expected one.

**Comment by 5ulo** [comment]
I understood it correctly, but as you can see in the Codepen, the title is only above the back button.. changing `levelTitleAsBack` to `true` or `false` does nothing.

**Comment by 5ulo** [comment]
sorry I see the change now.. So I didn't understood it correctly.
I thought when I open eg. `Magazines` menu item, there should be back button called `Magazines` and not by the `navTitle` (`All categories` in this example)

**Comment by somewebmedia** [comment]
> sorry I see the change now.. So I didn't understood it correctly.
> I thought when I open eg. `Magazines` menu item, there should be back button called `Magazines` and not by the `navTitle` (`All categories` in this example)

Well the previous level is _All Categories_, ant the current is _Magazines_, so how would back button `Magazines ⇦` make any sense?
