### ISSUE TITLE
Uncaught TypeError: hcOffcanvasNav is not a constructor

### ISSUE THREAD

**Issue by petewulf** [somewebmedia/hc-offcanvas-nav#53]
Hey there,

i just cant get this plugin to work - i'm always getting the same error:

**Uncaught TypeError: hcOffcanvasNav is not a constructor**

Its the same with vanilla and jQuery.

My version is:  **6.0.4**

Thanks for any help.
Daniel

**Comment by somewebmedia** [comment]
Can you please state more details, whats your dev environment, how are you initiating it?

**Comment by petewulf** [comment]
Yes sure:

Windows 10 with Chrome Version 86.0.4240.111
hcOffcanvas 6.04 via NPM
jQuery V 3.5.1

I tried initiating with both methods exactly like described in the docs:

Vanilla:
```
document.addEventListener('DOMContentLoaded', function() {
  var Nav = new hcOffcanvasNav('#main-nav', {
    disableAt: 1024,
    customToggle: '.toggle',
    navTitle: 'All Categories',
    levelTitles: true,
    levelTitleAsBack: true
  });
});
```
and

jQuery:
```
jQuery(document).ready(function($) {

  $('#main-nav').hcOffcanvasNav({
    disableAt: 1024,
    customToggle: $('.toggle'),
    navTitle: 'All Categories',
    levelTitles: true,
    levelTitleAsBack: true
  });

});
```

Both methods lead to the same error when initiating:

![error](https://user-images.githubusercontent.com/6872322/97482509-87228380-1956-11eb-9c80-83f0b407907a.PNG)

Thanks!
Daniel

**Comment by somewebmedia** [comment]
If you are using NPM, are you also using some kind of compiler for your scripts like Gulp, Babel etc? How are you including the script exactly?

**Comment by petewulf** [comment]
Yes i'm using gulp to merge my scripts together - but without any transpiler or compression, just a plain merge so this should not be the source of the problem.

I already included the Script directly from the NPM folder without any modification which leads to the same error.
The script is included via <script src="..."> tag, nothing special here.

The Object "hcOffcanvasNav" is available in the DOM but not instantiable. I can debug it which returns the object declaration:

![debug](https://user-images.githubusercontent.com/6872322/97551102-d3aba480-19d2-11eb-8d45-574ffb014ca1.PNG)

Thanks,
Daniel

**Comment by somewebmedia** [comment]
Ahh I see. The problem was that you included the source script (from the `src` dir) which had wrongly written constructor function. I fixed it now, but nonetheless you should consider using the script from the `dist` dir because that is the production script which is properly compiled and intended for use.

**Comment by petewulf** [comment]
That was the cause of the issue, now it workes perfectly. 
I didnt't realized that i was using the false source directory sorry for the inconvenience and thanks much for your help!

Daniel
