### ISSUE TITLE
Open menu with multiple elements with same toggle class

### ISSUE THREAD

**Issue by markgenest** [somewebmedia/hc-offcanvas-nav#56]
This is a an awesome menu!!! Thanks for all the hard work! 

I have a question regarding using a toggle class in multiple locations on the page. If you apply a toggle class to multiple elements on the page, the menu should open on any of them. However, the menu only seems to function with a single toggle element, even though there are multiple elements with the same toggle class.

Is there a way to activate the menu with multiple elements with the same toggle class?

Thanks so much!

**Comment by somewebmedia** [comment]
I've added the possibility of multiple toggles in the latest release. Use the latest version, it should work now.

**Comment by markgenest** [comment]
Yes! It works!! Thanks so much!!!
