### ISSUE TITLE
Close nav is not on top of menu

### ISSUE THREAD

**Issue by maddorris** [somewebmedia/hc-offcanvas-nav#59]
Hi,

one small issue i can't fix - close button appearing on the second place right after Home menu link. Do you have probably any idea what could cause it?

Nav title
-----
Home
-----
Close
-----
Other nav item
------
etc
------

Back button after you click deeper is then on the right place.

Thanks in advance for any support.

**Comment by maddorris** [comment]
Update - it's not a bug its a feature: insertClose: 0 solves the issue =)

**Comment by maddorris** [comment]
One question i have - is it possible to open menu on current active page level and not each time from start?

Thanks.

**Comment by somewebmedia** [comment]
Yes, check the [`data-nav-active`](https://github.com/somewebmedia/hc-offcanvas-nav#data-attributes) attribute.

If you're using WordPress I've wrote a out of the box working [code](https://github.com/somewebmedia/hc-offcanvas-nav#wordpress-data-attributes-integration).

**Comment by maddorris** [comment]
Thank you. Ill check on this. Im Working basicaly with joomla, but i think i will get this working =)

**Comment by maddorris** [comment]
Unfortunately it didnt work for me. so i was able to add data-nav-active to last active <li>-element, but it still open from start. 
So my structure is no like
<ul>
<li>menu 1<7li>
<li> menu 2 
<ul>
   <li data-nav-active>Menu 2.1</li> 
</ul>
</ul>

Any help is very appreciated =)

**Comment by somewebmedia** [comment]
Try it like this:

```html
<ul>
   <li>menu 1<7li>
   <li data-nav-active> menu 2 
      <ul>
          <li>Menu 2.1</li> 
     </ul>
    </li>
</ul>
```
And if you're using jQuery to add the attribute, be sure to add it before initiating the Nav.

**Comment by maddorris** [comment]
Hi, thamks for advise, but unfortunately this didnt woked for me.

I did tryed to add data-nav-axctive to current active li, to his ul-parent or to ul-li-parent - all of this didnt worked. 

I did checked hc-offcanvas-nav.js and didnt find any implementation for data-nav-active and data-nav-highlight. Can it be this is not inplace in git-version? Cause id did tryed on your demo as well and wasn't lucky as well...

And on emore question i have - is there the way to told that not only arrow expand sub items but whole nav item? Ie if there is no content for parent menu item that its only expand menu on click.

Thanks for your support.

**Comment by somewebmedia** [comment]
I've just noticed how you are using jQuery `attr()` to add attribute. You must use it like this `.attr('data-nav-active', true)`

**Comment by maddorris** [comment]
I do it like: 
`$("#main-nav ul.menu li.active.parent:last").attr("data-nav-active","");`

And adding this attribute works very well. But it doesnt affect how the nav is working.

**Comment by somewebmedia** [comment]
So, have you tried using the `true` instead of `''`?

**Comment by maddorris** [comment]
This doesnt help. What i noticed - your script create a clone of original navigation and hide the origin one. So i have two navs - hidden and one created by script. In origin i see all by system or via script added attributes and Id's. In by script cloned nav all these  are missing. I gues this is the reason why it doesnt work. 

Hovever i cant add id an data attributes to cloned nav, cause i have to do it before you it will be initialized, as you told.

In your demo i saw this is not the case, that nav will be cloned, so is it normal or i havw some bigger issue there?

Thank you

**Comment by somewebmedia** [comment]
> In cloned nav all these are missing. I gues this is the reason why it doesnt work.

Nope this is as it should be. Something else is troubling you.

I've just checked the data attributes with the repository demo and everything works as expected. So in order to help you, you would have to provide me with some demo I can live test.

**Comment by maddorris** [comment]
did send you via mail.

**Comment by somewebmedia** [comment]
For anyone reading, the problem was caused by the usage of the much older version of the plugin.
