### ISSUE TITLE
Plugin does not return plugin object.

### ISSUE THREAD

**Issue by merakmarey** [somewebmedia/hc-offcanvas-nav#6]
Hello

Somehow the plugin is not returning the correct/complete object. See screenshots.
On first screen the object does not contain the close,isOpen,open, etc function .
So, I made a jsfiddle and on that does show the functions..(third screenshot).
If you look at the watch section on 1st and 2nd screen you will see that the return is a regular jQuery object, not the expected plugin object, why?

 * Version: 3.1.2 - Chrome

![image](https://user-images.githubusercontent.com/8477219/47543867-42206e00-d8b2-11e8-886b-87791eed9ed8.png)

![image](https://user-images.githubusercontent.com/8477219/47587648-8dc62c80-d931-11e8-9c45-46f7976c7b18.png)

![image](https://user-images.githubusercontent.com/8477219/47543893-62502d00-d8b2-11e8-8c46-bf64655010e7.png)

**Comment by somewebmedia** [comment]
Can you explain what do you think by "expected plugin object"?

The current returning object is jQuery object on which I attached the plugin methods. I did it like this so I wouldn't have to bloat the jQuery namespace.

This also means once you got back this object, you can call the plugin methods only on it.

**Comment by merakmarey** [comment]
If you take a look at the screenshots on the watch section, you will see that the watch on variable containing the object (called MainNavMenu) does not contain a definition for the method close, that means that the method .hcOffcanvas called on the line 356 is not returning the correct object, which should contain a method "close".

**Comment by somewebmedia** [comment]
Ah I see what you mean. How is it possible that it works for you in jsfiddle, but not in your project? Are you using the latest version in your project?

**Comment by merakmarey** [comment]
New version returned the correct object. Thanks. Still, going to open new issue, sorry :P
