### ISSUE TITLE
Allow changing toggle button class

### ISSUE THREAD

**Issue by ronilaukkarinen** [somewebmedia/hc-offcanvas-nav#61]
If `customToggle` is used, toggled class should be also possible to define. Now it's `toggle-open` and if using for example [hamburgers](https://jonsuh.com/hamburgers/) via npm the animations won't work because in hamburgers they use `.is-active` class. My suggestion is to allow to change this. Now it's hardcoded.

**Comment by somewebmedia** [comment]
Done! Newest version `v6.1.2` use the option `activeToggleClass`

**Comment by ronilaukkarinen** [comment]
Wow, that was fast, thanks! ❤️
