### ISSUE TITLE
Right swipe gesture does not work

### ISSUE THREAD

**Issue by telinger** [somewebmedia/hc-offcanvas-nav#63]
Hello,
first of all I would like to thank you for awesome mobile menu, I really like it. I noticed that swipe gesture from right side does not work in our project.  I found out the same problem in your demo ([https://somewebmedia.github.io/hc-offcanvas-nav/](url)). When you disable push content setting and set position: left, swipe gesture works but if you change position to right, swipe gesture does not work anymore. Same problem is present when pust content is active and position is set to right, if it is left it also works as intended. Thank you.

**Comment by somewebmedia** [comment]
Fixed with the latest version.
