### ISSUE TITLE
Angular.js dropdowns break in chrome. Overrides to _eventListeners and addRemoveListener causing conflicts

### ISSUE THREAD

**Issue by mowens3** [somewebmedia/hc-offcanvas-nav#64]
In hc-offcanvas-nav.helpers.js,

`Node.prototype.addEventListener = addRemoveListener('add');`

This line of code seems to have greater implications. Now all elements on the page respond to the addRemoveListener function. 

As a result it has to be removed and/or patched to work with angular.js dropdowns and other javascript impacted by this.

Any ideas to improve this or limit the scope of this code? I also had to remove _eventListeners due to their dependency on this function.

With this code removed everything still functions as expected. I'm guessing I removed functionality related to automatically opening the menu at a specific level/item.

**Comment by mowens3** [comment]
found a way to wrap all this in an isolated container

**Comment by somewebmedia** [comment]
It was done so the events (if any) in the original menu could be cloned.

> found a way to wrap all this in an isolated container

Can you share your solution?
