### ISSUE TITLE
Render out HTML Object in Nav Title

### ISSUE THREAD

**Issue by BrandanKing** [somewebmedia/hc-offcanvas-nav#67]
Hi,

You added the ability to render out a HTML element as NavTitle [#47](https://github.com/somewebmedia/hc-offcanvas-nav/issues/47) Is it possible that you could update your doc / show me how to actually create the JS element required to make this render properly please.

Thanks

**Comment by somewebmedia** [comment]
Vanilla JS:
```js
var title = document.createElement('div');
title.appendChild(document.createTextNode('Hi there!'));

var Nav = new hcOffcanvasNav('#main-nav', {
  navTitle: title
});
```

jQuery:
```js
var Nav = new hcOffcanvasNav('#main-nav', {
  navTitle: $('<div>Hi there!</div>')
});
```
