### ISSUE TITLE
Expanded nav on large screens and collapsed on small screens

### ISSUE THREAD

**Issue by abstractindia** [somewebmedia/hc-offcanvas-nav#68]
I am trying to make the nav expanded for large screens (above 768px) and collapsed nav on small screens (below 768px) which can be opened by taping on toggle. The option `expanded : true` is making the nav expanded even on small screens. What option should I tweak to make this possible?

**Comment by somewebmedia** [comment]
I'll probably have to introduce a new option to the plugin.
