### ISSUE TITLE
Content stripped from nav after plugin initialization

### ISSUE THREAD

**Issue by merakmarey** [somewebmedia/hc-offcanvas-nav#7]
See http://jsfiddle.net/e7p5t0xy/

On original nav element, there is a li with class "divider". This li contains a div with class "addremove-multi" and some elements inside.

After plugin initialization, the content of the li.divider changes to an empty a tag.

Version 3.3.1 - Chrome 70

**Comment by somewebmedia** [comment]
This is because I'm not including item's content if it's `<div>`, because it's common practice to wrap submenus to divs. Use span instead: http://jsfiddle.net/e7p5t0xy/1/
