### ISSUE TITLE
how to add multiple menu

### ISSUE THREAD

**Issue by denthemes** [somewebmedia/hc-offcanvas-nav#70]
how to add multiple menu in single page

**Comment by somewebmedia** [comment]
Just call HC Off-canvas Nav on each menu.

```js
var Nav1 = new hcOffcanvasNav('#main-nav', {...});
var Nav2 = new hcOffcanvasNav('#sub-nav', {...});
var Nav3 = new hcOffcanvasNav('#sub-sub-nav', {...});
```

**Comment by denthemes** [comment]
please provide some demo

**Comment by somewebmedia** [comment]
Sorry I won't do that. You have the examples, just try it yourself. You can do it, I believe in you 😊

**Comment by denthemes** [comment]
thank you,..!!! perfectly working...

**Comment by denthemes** [comment]
multiple menu not working in elementor
