### ISSUE TITLE
Preven menu closing when press "Esc"

### ISSUE THREAD

**Issue by kapdom** [somewebmedia/hc-offcanvas-nav#73]
Hi.
How to prevent menu closing when press "Esc"?

**Comment by somewebmedia** [comment]
Currently, you can't. I could add an option to disable this feature.

**Comment by kapdom** [comment]
So please, if it's possible add this option.
Thank you.
When are you going to add this option?

Regards

**Comment by somewebmedia** [comment]
As soon as I get some free time. It's a small feature, so it shouldn't take me long.

**Comment by somewebmedia** [comment]
Sorry for the delay. The new option `closeOnEsc` has been added, just set it to `false`.

**Comment by kapdom** [comment]
Thank you.
