### ISSUE TITLE
How to add html object to navTitle ?

### ISSUE THREAD

**Issue by Parvaz19** [somewebmedia/hc-offcanvas-nav#76]
I try to add html to nav Title like:
```
$('#main-nav').hcOffcanvasNav({
           ....
           ....
            navTitle: '<div class='text-bold'>My Website</div>',
            });
```

but it's not work.
how do that?

thanks alot,

**Comment by somewebmedia** [comment]
You need to pass an html object. Take a look here: https://github.com/somewebmedia/hc-offcanvas-nav/issues/67
