### ISSUE TITLE
BACK menu item not accessible with TAB key

### ISSUE THREAD

**Issue by 5ulo** [somewebmedia/hc-offcanvas-nav#77]
When I open `hc-offcanvas-nav` with the keyboard and I navigate with keyboard to the second level of navigation (panel 2), I am unable to focus on `back` item to go -1 level up. Sure I can hit ESC, but this item should be focusable though.

And now the strange part. The back nav item is focusable ONLY when option `insertBack` != `true`, `false` or `0`.
So for example `insertBack: -1` is working.
This bug is also here: https://somewebmedia.github.io/hc-offcanvas-nav/

**Comment by somewebmedia** [comment]
Fixed in the latest version.
