### ISSUE TITLE
Bug: click event called twice.

### ISSUE THREAD

**Issue by merakmarey** [somewebmedia/hc-offcanvas-nav#8]
Expected behavior, one alert. Actual behavior: Two alerts.

On same example, click inside span inside .123 span does not trigger click.

http://jsfiddle.net/m08kfwvr/1/

**Comment by merakmarey** [comment]
Correction: Second issue (not triggering a click) does work. My mistake.

**Comment by somewebmedia** [comment]
The offcanvas nav is somewhat a copy of the original one, so when you attach click events on the items with the class name globally, they somehow attaches themselves twice in the new nav.

You should attach your events on the main nav before calling the plugin, or just on the offcanvas nav.

http://jsfiddle.net/m08kfwvr/2/

That being said, there was a bug when I didn't copy events from the non link elements inside the nav. It's fixed now with the new version.

**Comment by merakmarey** [comment]
So for elements added after the plugin call will not work?

**Comment by somewebmedia** [comment]
It will if you call `update` method on the plugin, so it can refresh everything.
