### ISSUE TITLE
Menu scroll / overflow

### ISSUE THREAD

**Issue by topperharley8** [somewebmedia/hc-offcanvas-nav#86]
How to set the menu / submenu to scroll?

I found an old snippet, which works with:
https://bootsnipp.com/snippets/dp5e9

I haven't found the difference / solution yet.

Thx.

**Comment by somewebmedia** [comment]
If you mean if the content of the menu is larger than the page height, you should be able to scroll.

**Comment by topperharley8** [comment]
Colud you check it?

[https://abident.premiummedia.hu/csapatunk.html](url)

Thx.

**Comment by topperharley8** [comment]
Ok. I found a solutiond. 
I used custom css, 

`.hc-offcanvas-nav.nav-levels-overlap .nav-content {
    display: table-cell;
}`

Just erase, and than work it.
Sorry, thanks your reply.
