### ISSUE TITLE
Can't add a search box to the menu

### ISSUE THREAD

**Issue by Asadlerpwcom** [somewebmedia/hc-offcanvas-nav#9]
I am trying to add a search box to the menu, however it does not show on the menu.

The code is completely removed by the plugin, how do i go about adding this?

This is the code i'm trying to add within the nav tag:

```
    <ul class="search">
        <li>
            <div class="input-group input-group-sm pt-1 w-75">
                <input type="text" class="form-control search-form-control" aria-label="Amount (to the nearest dollar)">
                <div class="input-group-append">
                    <span class="input-group-text search-icon">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </span>
                </div>
            </div>
        </li>
    </ul>
```

**Comment by somewebmedia** [comment]
It's a bug. I'll prepare a fix for that.

**Comment by somewebmedia** [comment]
@Asadlerpwcom new version is out, can you please check it and let me know if everything is working properly now. Thanks.

**Comment by Asadlerpwcom** [comment]
Works perfectly thanks!

![image](https://user-images.githubusercontent.com/31763294/47921074-9ecfea00-deab-11e8-93d5-b31d851e2e34.png)
